# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate and publish packages
on:
  release:
    types: [created]
    tags:
      - 'v*.*.*'
jobs:
  publish-go:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
      - name: Generate Go module
        run: ./generate_go.sh
      - name: Publish package
        run: echo "skipping for now"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-maven:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Add version from release to env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Add release to Maven package template
        run: |-
          cd generated/maven/lib
          pwd; echo "cat build.template.gradle | sed s/{{VERSION}}/${RELEASE_VERSION}/g > build.gradle2"
