name: Maven
on:
  release:
    types: [created]
    tags:
      - '*.*.*'
jobs:
  generate-and-publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Get publish version from env
        id: publish_version
        run: |-
          RELEASE_VERSION_WITH_V=${GITHUB_REF#refs/*/}
          echo ::set-output name=value::${RELEASE_VERSION_WITH_V:1}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Add publish version to Maven package template
        env:
          VERSION: ${{ steps.publish_version.outputs.value }}
        run: |-
          cd generated/maven/lib
          cat build.template.gradle \
            | sed s/{{VERSION}}/${VERSION}/g > build.gradle
      - name: Generate package
        run: ./generate_maven.sh
      - name: Publish package
        run: |-
          cd generated/maven
          gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
